### ISSUE TITLE
Status bar is always white

### ISSUE THREAD

**Issue by utiq** [apache/cordova-plugin-statusbar#109]
How can I make status bar translucent? (I don't want to do it in config.xml, I also tried)
Whatever change I make, it doesn't reflect in the app. So far I tried this.

`StatusBar.styleLightContent();`
I also played with `StatusBar.overlaysWebView(false);`
The only way it works is if I set it up like this, `StatusBar.styleDefault();`, but it shows a white bar with black text. 

The result is always this, a white status bar with no text (iOS 12, Cordova 8.1.1):
![img_1338](https://user-images.githubusercontent.com/1144196/48235716-d17a5680-e373-11e8-9e1d-f955b19b29cb.PNG)

**Comment by Dwarfex** [comment]
Same Problem here.
However: This plugin fixed it for me: https://github.com/jcesarmobile/cordova-plugin-disable-ios11-statusbar

I would expect this to work with only this library.

**Comment by Kappyh** [comment]
I have the same issue and I can't change the color of the status bar for any other color.
Just happens in iOS, in Android works.

**Comment by Dwarfex** [comment]
I also tried several "solutions" advised here: (https://stackoverflow.com/questions/46232812/cordova-app-not-displaying-correctly-on-iphone-x-simulator) 

However "padding-top: env(safe-area-inset-top);" is not working for me as it does nothing to my layout.

I also noticed, that 'viewport-fit=cover' is not part of the displayed html anymore (altough part of the original html file) when inspected with Safari.
![bildschirmfoto 2018-11-09 um 15 00 36](https://user-images.githubusercontent.com/721721/48266896-13b59d80-e431-11e8-8701-7352b28dd534.png)

**Comment by utiq** [comment]
I fixed it doing this:
https://stackoverflow.com/a/46232813/751524

**Comment by Dwarfex** [comment]
@utiq What exactly where the steps, that fixed it for you?

**Comment by utiq** [comment]
@Dwarfex  Exactly the steps that Stackoverflow response says.

**Comment by diegodotta** [comment]
Basically, you need to add splashscreen plugin to fix this issue @Dwarfex.
I was also having a weird issue using "window.cordova" before StatusBar, like window.cordova.StatusBar. This works well on Android, but not on iOS.

**Comment by Dwarfex** [comment]
@diegodotta I hoped so - but i already have added the plugin.

- I use viewport-fit=cover
- i use the splashscreen plugin with a "<splash src="res/screens/ios/Default@2x~universal~anyany.png" />" setting
so my application looks like the second image on the stackoverflow link 
https://i.stack.imgur.com/VNFYb.png

But the variable "env(safe-area-inset-top)" seems to be "0" or not set as it has no effect on the layout. (even when used on simple divs)

**Comment by jcesarmobile** [comment]
That's not the status bar, is the safe area, if you want to get rid of it, add `viewport-fit=cover` to your viewport meta tag as a lot of people already commented.

**Comment by selirion04** [comment]
> That's not the status bar, is the safe area, if you want to get rid of it, add `viewport-fit=cover` to your viewport meta tag as a lot of people already commented.

But what should i do if i don't want cover, but jusst want to change color? In mobile safari this area has background-color of body tag. In cordova it's always white.
