### ISSUE TITLE
Status bar don't overlay web view in Ionic

### ISSUE THREAD

**Issue by brunojs02** [apache/cordova-plugin-statusbar#111]
Ionic: 3.20.0
Cordova: 8.0.0
Cordova-ios: 4.5.5
Plugin version: 2.4.2
iOS version: 11.4 (emulator)

Configurations:
StatusBar.overlaysWebView(true);

I want the status bar overlay web view, but for some reason, my status is setting to white.

Result: [image](https://imgur.com/a/KIMFkiy)

**Comment by janpio** [comment]
What plugin version are you using?
What iOS version are you testing on?
Did you remote debug the problem and inspect the code to see if the webview is actually full size? (See instructions at https://ionic.zone/debug/remote-debug-your-app#ios)

**Comment by janpio** [comment]
> web view is not in full screen, how can I make it? PS: I don't wanna hide status bar.

Those two statement pretty much contradict themselves. What exactly do you want to do?

**Comment by brunojs02** [comment]
I want the status bar color use the same color of navbar.

**Comment by janpio** [comment]
So the status bar should be a light grey?

Use https://github.com/apache/cordova-plugin-statusbar#configxml `StatusBarBackgroundColor` or https://github.com/apache/cordova-plugin-statusbar#statusbarbackgroundcolorbyhexstring

**Comment by jcesarmobile** [comment]
That's not the status bar, is the safe area, if you want to get rid of it, add `viewport-fit=cover` to your viewport meta tag
