### ISSUE TITLE
Incorrect Status Bar Position on iPad Pro 3rd Gen

### ISSUE THREAD

**Issue by cvanem** [apache/cordova-plugin-statusbar#120]
The status bar appears correclty in the simulator, but when deployed to an actual device it is incorrect.  
![img_0011](https://user-images.githubusercontent.com/24579103/50388350-c3d52200-06d0-11e9-8f7c-6359c64c0f1c.jpeg)

This only happens on the new iPad Pro 12.9 Gen 3 Model.  
I also verified the correct behavior on a normal iPad 2018 and an iPhone XS Max without issues.

**Comment by cvanem** [comment]
This turned out to be an issue with cordova-plugin-inappbrowser.  Closing

**Comment by mayank-aika** [comment]
Hi, @cvanem - I am facing similar issue, what did you do to resolve this issue

https://stackoverflow.com/questions/54230742/status-bar-not-sticking-to-top-on-some-ipads

**Comment by mayank-aika** [comment]
NVM, got you solution from https://github.com/apache/cordova-plugin-inappbrowser/issues/382

**Comment by kclarke14** [comment]
I don't think this should have been closed as an issue with inappbrowser. I am only using statusbar and I have this issue on iPad Pro 3rd Gen.

**Comment by MayankLogiciel** [comment]
@kclarke14 - Actually this issue is with splashscreen plugin. On iOS app, you need to move away from using Legacy way launch images. For more details just check splash screen plugin.

**Comment by kclarke14** [comment]
We do not use the splashscren plugin either - this is truly an issue with the statusbar showing midway into our app on the iPad

**Comment by MayankLogiciel** [comment]
@kclarke14 - Not neccessary to use splash screen pluging, just read its docs and use splash screens the new storyboard way, thats it.

**Comment by MayankLogiciel** [comment]
![4C7C913B-D73B-4B3C-9247-178104E9AD12](https://user-images.githubusercontent.com/8719380/56156529-15d0e900-5fdb-11e9-8d5c-e83f162fac3e.jpeg)


@kclarke14  Check this from SplashScreen plugins Github docs.
