### ISSUE TITLE
Plugin not working correctly IOS

### ISSUE THREAD

**Issue by stefangroenew** [apache/cordova-plugin-statusbar#122]
I'm using the following config.xml

`<plugin name="cordova-plugin-statusbar" />`
`<preference name="StatusBarOverlaysWebView" value="false" />`
`<preference name="StatusBarBackgroundColor" value="#000000"/>`
`<preference name="StatusBarStyle" value="lightcontent" />`

The statusbar text is white, thats OK but the statusbar itself is not black (#000000) as defined in the config.xml It is transparent... 

Using: 

`<preference name="phonegap-version" value="cli-8.0.0" />`

Device:  IOS12 on iPhone6
Phonegap Build

Screenshot: https://i.imgur.com/IQejdi5.png
When the keyboard pop up the content scrolls behind the statusbar content... :/

**Comment by bvosk** [comment]
@stefangroenew Did you find any workaround to this? This has been a big problem for me with multiple apps. We've had to revert to earlier version of the Cordova CLI.

**Comment by stefangroenew** [comment]
@bvosk Unfortunately I have not found a solution yet. Which version of Phonegap Build do you use? Can you send the config.xml code snippet? Thanks!

**Comment by bvosk** [comment]
@stefangroenew Using this preference in the `config.xml` file makes the status bar work for us:

```xml
<preference name="phonegap-version" value="cli-6.5.0" />
```

**Comment by bvosk** [comment]
@breautek That worked for me, so it seems you're right. Thanks so much for the help!

**Comment by stefangroenew** [comment]
@breautek @bvosk Thank you for your comments, unfortunately the Javascript solution after the DeviceReady will not work (on IOS). 

I have set a lime color that works well on Android. 

`StatusBar.overlaysWebView(false);
StatusBar.backgroundColorByHexString("#adf907");`

However, this does not work on IOS. The color is visible a verry short time. See this video:
[https://youtu.be/RS_5hFCWHSU](https://youtu.be/RS_5hFCWHSU)

Any idea? Thanks! Stefan

**Comment by stefangroenew** [comment]
@breautek  @bvosk  I found the issue! The Javascript solution was working but the framework I use was overwrite some settings. More info: 

[https://framework7.io/docs/statusbar.html#statusbar-styling](https://framework7.io/docs/statusbar.html#statusbar-styling)

Thanks again for the help! Stefan

**Comment by breautek** [comment]
@stefangroenew The javascript solution wasn't really a solution. More like a workaround. The real solution in my opinion is to fix the native objective-c code to pull in the preference values from config.xml. That is however outside of my knowledge. I'm not an experienced iOS developer, nor do I have a personal iphone or mac to use to test with.

**Comment by bvosk** [comment]
@stefangroenew I agree with @breautek, would better to leave this open because it should respect the preference in the `config.xml` file.

**Comment by saschwarz** [comment]
Interestingly, there is an (old) ionic fork of this repository which resizes the views when the statusbar setting changes: https://github.com/ionic-team/cordova-plugin-statusbar/commit/556cfec944b8e7e8e5527f919033b9f3e13cbfa3#diff-6c2a2e39ff0170e7471ce1d9aff1b5baR216

**Comment by breautek** [comment]
I did a little bit more investigating and found that this isn't indeed only an iOS issue.

On Android, `StatusBarBackgroundColor`, `StatusBarStyle` both do appear to work on startup. `StatusBarOverlaysWebView` however does not. Additionally Android does not use overlay mode by default, which is what the documentation says.

**Comment by jcesarmobile** [comment]
I can't reproduce on latest version of the plugin, cordova and cordova-ios.
The code for checking the preference has always been there according to the git blame
9 years ago https://github.com/apache/cordova-plugin-statusbar/blame/3795486e33a4a9113773d5e688374d142f93828c/src/ios/CDVStatusBar.m#L113-L115
7 years ago https://github.com/apache/cordova-plugin-statusbar/blame/1672883a7fda51e73069d6f350393bb2719228e3/src/ios/CDVStatusBar.m#L190-L196

As far as I remember phonegap build had a problem with preferences not working and some users mention phonegap build, so it was probably the issue.
If somebody still faces the issue with latest cordova, cordova-ios and cordova-plugin-statusbar, please, create a new issue and provide a sample app where the issue can be reproduced.
