### ISSUE TITLE
JSHint vs ESLint

### ISSUE THREAD

**Issue by timbru31** [apache/cordova-plugin-statusbar#125]
This project uses JSHint - should ESLint be used (as recommended via https://issues.apache.org/jira/browse/CB-12895) to maintain a consistent linting across all Cordova plugins?

**Comment by janpio** [comment]
Yeah, best compare how other plugins do it - the newer the configuration, the better ;)

**Comment by timbru31** [comment]
Most of them use ESLint, too. So I guess that one "wins".

**Comment by janpio** [comment]
Now: https://github.com/apache/cordova-plugin-statusbar/issues/141
