### ISSUE TITLE
Transparent status bar?

### ISSUE THREAD

**Issue by Djery-Tom** [apache/cordova-plugin-statusbar#133]
### Issue Type
Please how can get a transparent status bar in my ionic app 

- [x] Support Question

### Environment, Platform, Device
Ionic 4.1
Cordova plugin status bar 2.4.2

**Comment by jcesarmobile** [comment]
use `<preference name="StatusBarOverlaysWebView" value="true" />` or `StatusBar.overlaysWebView(true);`
