### ISSUE TITLE
StatusBar.hide not working when open inappbrowser

### ISSUE THREAD

**Issue by aahedi** [apache/cordova-plugin-statusbar#146]
StatusBar.hide not working when open inappbrowser

**Comment by jcesarmobile** [comment]
Can you provide more details like code and screenshots? it's not clear what the problem is or how to reproduce

**Comment by piterio19** [comment]
@jcesarmobile I can add more details as I'm having the same issue. 

StatusBar is working normally (e.g. I can disable/enable overlayWebView, show()/hide it, change background color) until I show an InAppBrowser.

Once I show() the InAppBrowser the StatusBar changes to its default (i.e. translucent white background, black text) and cant hide/show, change colour, etc. If I then hide the InAppBrowser then StatusBar returns to the state I programmed it to in index.js and its methods work again normally.

I'm building with PG Build.

**config.xml (excerpt):**
`    <preference name="phonegap-version" value="cli-7.1.0" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="android-minSdkVersion" value="19" />
    <preference name="android-targetSdkVersion" value="28" />
    <preference name="orientation" value="portrait" />
    <preference name="android-build-tool" value="gradle" />
    
    <plugin name="cordova-plugin-device" source="npm" spec="2.0.3" />
    <plugin name="cordova-plugin-statusbar" source="npm" spec="2.4.3" />
    <plugin name="cordova-plugin-whitelist" source="npm" spec="1.3.4" />
    <plugin name="cordova-plugin-dialogs" spec="2.0.2" />
    <plugin name="cordova-plugin-network-information" spec="2.0.2" />
    <plugin name="cordova-plugin-inappbrowser" spec="3.1.0" />
    <plugin name="phonegap-plugin-push" source="npm" spec="2.1.2">
        
        <variable name="FCM_VERSION" value="15.0.+" />
    </plugin>
    <plugin name="cordova-plugin-customurlscheme" source="npm">
        <param name="URL_SCHEME" value="protocolocontaminacion" />
    </plugin>
`
**index.js (excerpt):**
`  onDeviceReady: function() {
        
        console.log("Entering onDeviceReady. Connection type: " + navigator.connection.type);
        
        // Configure StatusBar on iOS. To change colour overlay must be false.
        StatusBar.overlaysWebView(false);
        if (device.platform == 'iOS') {
            //StatusBar.styleDefault();
            StatusBar.backgroundColorByHexString("#70ca7a");
        }        
`

**Comment by Saqib92** [comment]
facing same issue only in IPAD's. opening IAB showing statusbar but on close i call statusbar.hide it shows white black line at top.
