### ISSUE TITLE
Cannot add cordova-plugin-statusbar  in command cli.

### ISSUE THREAD

**Issue by James06** [apache/cordova-plugin-statusbar#150]
![image](https://user-images.githubusercontent.com/11706138/63678268-6aa22d00-c821-11e9-8612-1b07d7d0818d.png)
![image](https://user-images.githubusercontent.com/11706138/63678288-7d1c6680-c821-11e9-8323-4f2907382093.png)
How to resolve this problem?
Is there any way to add plugin.xml of the cordova-plugin-statusbar

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
