### ISSUE TITLE
Cant set desired statusbar properties

### ISSUE THREAD

**Issue by TerekhovAI** [apache/cordova-plugin-statusbar#151]
# Bug Report
Cant get desired status bar properties

## Problem
I need statusbar background to be transparent, and font-color to be black

### What does actually happen?
Background color is black or any other color i set, but no any opacity, ever.

## Information
According to docs, i tried (in config.xml)
1)  <preference name="StatusBarOverlaysWebView" value="true"/> . (which is actually 'true' by default)
<preference name="StatusBarStyle" value="default" />
This should make statusbar transparent.
But i get black solid background with no transparency.
2) <preference name="StatusBarOverlaysWebView" value="false"/>
also i set hex color value via ARGB
<preference name="StatusBarBackgroundColor" value="#00ffffff" />
alternatively tried via StatusBar.backgroundColorByHexString('#00FFFFFF') in index.jsx file
in this case i dont get any transparency at all, seems like ARGB value is not being recognised correctly.

### Environment, Platform, Device
phone with Android 8.1.0

### Version information
I make hybrid app in React,
Cordova Platforms : android 8.0.0, ios 5.0.1
"cordova-plugin-statusbar": "^2.4.3",

## Checklist
- [x] I searched for existing GitHub issues
- [x] I included all the necessary information above

**Comment by breautek** [comment]
To get the statusbar transparent, normally you would use the following config.xml property

```xml
<preference name="StatusBarOverlaysWebView" value="true" />
```

**But** this is currently broken, PR https://github.com/apache/cordova-plugin-statusbar/pull/142 is awaiting review which fixes the android platform to read the config.xml properly.

Two workarounds are available:
1. Use the JS API to enable the overlay via `StatusBar.overlaysWebView(true);` after the `deviceready` event fires.
2. Apply the PR to your own fork of the statusbar.
