### ISSUE TITLE
Two Status Bar Show in my ios App.

### ISSUE THREAD

**Issue by jeganwbc** [apache/cordova-plugin-statusbar#153]
**I set the Statusbar overlay false and it shows two status bar.** 

![](https://lh3.googleusercontent.com/-2GHeM4qZmLc/XXjM1-e8UTI/AAAAAAAAAIw/oMQszJEJnSIVztqGURhlFJslIfNGEMN2gCK8BGAsYHg/s0/2019-09-11.jpg)

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
