### ISSUE TITLE
[iOS 13] Status Bar Style properties don't work when system dark mode is enabled.

### ISSUE THREAD

**Issue by Kinectech** [apache/cordova-plugin-statusbar#161]
# Bug Report

## Problem
When system dark mode is enabled in iOS 13, commands such as this.statusBar.styleDefault(), styleBlackOpaque(), etc. doesn't affect the color of the text in the status bar. It begins working again as soon as dark mode is disabled.
### What is expected to happen?
Those commands such as styleDefault() should affect the status bar text color regardless of system dark mode being able.

### What does actually happen?
The text color doesn't change

### Command or Code

This is the code pertaining to the statusbar in app.component.ts:
`const prefersDark = window.matchMedia('(prefers-color-scheme: dark)');
      prefersDark.addListener((mediaQuery) => this.themeControl(mediaQuery.matches));
      this.statusBar.overlaysWebView(true);
      this.statusBar.show();
      this.splashScreen.hide();`

This is the code which controls the theme of the app:
`  constructor(private rendererFactory: RendererFactory2, @Inject(DOCUMENT) private document: Document, private statusBar: StatusBar) { 
    this.renderer = this.rendererFactory.createRenderer(null, null);
  }`

 `   enableDark() {
    this.renderer.addClass(this.document.body, 'dark')
    this.statusBar.styleBlackTranslucent();
    Keyboard.setKeyboardStyle('dark')
  }`

  `  enableLight() {
    this.renderer.removeClass(this.document.body, 'dark')
    this.statusBar.styleDefault();
    Keyboard.setKeyboardStyle('light')
  };`

### Environment, Platform, Device
Observed on iOS 13.1.2 using ionic-v4 compiled to an IPA file on an iPhone XS 

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by MikeG96** [comment]
https://github.com/apache/cordova-plugin-statusbar/issues/148#issuecomment-538558631

Check this :)

**Comment by jcesarmobile** [comment]
Already reported on https://github.com/apache/cordova-plugin-statusbar/issues/148
