### ISSUE TITLE
Deprecate styleBlackTranslucent and styleBlackOpaque

### ISSUE THREAD

**Issue by jcesarmobile** [apache/cordova-plugin-statusbar#163]
`StatusBar.styleBlackTranslucent` and `StatusBar.styleBlackOpaque` just set the value to `UIStatusBarStyleLightContent` because their original values were deprecated by Apple on iOS 7. So makes no sense to have them anymore. We should deprecate or remove them.

**Comment by breautek** [comment]
I'd say deprecate now, remove in next major.

**Comment by brodybits** [comment]
I think the best solution would be to make a minor release branch where we make a minor release with the deprecation (not sure if this would be in log, documentation, or somewhere else), then plan to remove these in the next major release.

In case nobody has this extra time, which is my anticipation, then I would favor removing these in the next major.

**Comment by breautek** [comment]
If there is still a significant amount of time before the next major release then I think what @brodybits makes sense.

If the next major release is going out soon where it doesn't make sense to make a minor release, then I think we still just need to bite our lip and deprecate on that major, and remove on the following major. Generally speaking people don't like when things just disappears without a heads up.

And correct me if I'm wrong but I don't think this is a critical issue where Apple will start blocking apps for using a deprecated style.

**Comment by jcesarmobile** [comment]
No, the deprecated styles are not even used, all the options use the `UIStatusBarStyleLightContent` now

**Comment by mosababubakr** [comment]
what about if some one use dark contents in the app or like dark image in the background?

Should we use this preference in config.xml or i am wrong?

`<preference name="StatusBarStyle" value="blacktranslucent" />`

**Comment by jcesarmobile** [comment]
there are four possible values at the moment:
default: sets the status bar content (hour, battery, icons, etc) color to black
lightcontent, blackopaque, blacktranslucent: set he status bar content (text, hour, battery, icons, etc) color to white.
Since they all do the same, and blackopaque/blacktranslucent correspond to old native values that were deprecated by Apple on iOS 7, we plan to remove them in a future release.
So if you have `<preference name="StatusBarStyle" value="blacktranslucent" />`, use `<preference name="StatusBarStyle" value="lightcontent" />` as it does the same

**Comment by mosababubakr** [comment]
> there are four possible values at the moment:
> default: sets the status bar content (text, hour, battery, icons, etc) color to black
> lightcontent, blackopaque, blacktranslucent: set he status bar content (text, hour, battery, icons, etc) color to white.
> Since they all do the same, and blackopaque/blacktranslucent correspond to old native values that were deprecated by Apple on iOS 7, we plan to remove them in a future release.
> So if you have `<preference name="StatusBarStyle" value="blacktranslucent" />`, use `<preference name="StatusBarStyle" value="lightcontent" />` as it does the same

Thanks for your explain

I think the `blacktranslucent` mean that if your app has dark content, and i don't know that it is same to lightconent value.

Regards

**Comment by orgilbat** [comment]
I used this setting in config.xml
```
   <preference name="StatusBarBackgroundColor" value="#2C3A47" />
   <preference name="StatusBarStyle" value="lightcontent" />
   <preference name="StatusBarOverlaysWebView" value="false" />
```
Background color changed but text is still black. Do you know why it is not working?
