### ISSUE TITLE
Deprecate StatusBar.styleDefault or document iOS 13 behaviour

### ISSUE THREAD

**Issue by jcesarmobile** [apache/cordova-plugin-statusbar#165]
styleDefault no longer sets the text to black, instead it depends on the device mode set on the device.
If device is set to dark mode, default set the text to white.

So we should deprecate it or document this new iOS 13 behaviour.

**Comment by forumics** [comment]
edit CDVStatusBar.m
look for this line:
- (void) styleDefault:(CDVInvokedUrlCommand*)command


replace the whole method with
- (void) styleDefault:(CDVInvokedUrlCommand*)command
{
    if (@available(iOS 13.0, *)) {
        [self setStyleForStatusBar:UIStatusBarStyleDarkContent];
    } else {
        [self setStyleForStatusBar:UIStatusBarStyleDefault];
    }
}

**Comment by jcesarmobile** [comment]
Default should be the native default and we should add styleDark

https://github.com/apache/cordova-plugin-statusbar/issues/164

**Comment by rml125** [comment]
> edit CDVStatusBar.m
> look for this line:
> 
> * (void) styleDefault:(CDVInvokedUrlCommand*)command
> 
> replace the whole method with
> 
> * (void) styleDefault:(CDVInvokedUrlCommand*)command
>   {
>   if (@available(iOS 13.0, *)) {
>   [self setStyleForStatusBar:UIStatusBarStyleDarkContent];
>   } else {
>   [self setStyleForStatusBar:UIStatusBarStyleDefault];
>   }
>   }

WoooW! I had the same problem. This fix worked perfectly.

**Comment by jcesarmobile** [comment]
Please, don't comment things out of topic.

The issue is about deprecating styleDefault because the name is confusing (default value of statusbar is lightContent).
Or documenting the iOS 13 behaviour (i.e. default depends on the device mode, dark mode -> white, light mode -> black)
Or just make it always set the text to black as it used to, but in that case I think it would be better to add a new method `styleDark` and deprecate/remove the default one.

**Comment by forumics** [comment]
when i have the time, i will create a fork and implement your suggestion

**Comment by danielehrhardt** [comment]
> when i have the time, i will create a fork and implement your suggestion

https://github.com/codextde/cordova-plugin-statusbar-color-fix

**Comment by jcesarmobile** [comment]
closing since looks like people wants default to be black as it used to instead of native default.
That behavior has been fixed in https://github.com/apache/cordova-plugin-statusbar/pull/169https://github.com/apache/cordova-plugin-statusbar/pull/169
