### ISSUE TITLE
StatusBar.overlaysWebView(true) doesn't work in iOS 13

### ISSUE THREAD

**Issue by kkirby** [apache/cordova-plugin-statusbar#166]
# Bug Report

## Problem

Status bar isn't overlaying WebView when telling the plugin to do so.

### What is expected to happen?

Status bar should overlay the WebView when asking the plugin to do so

### What does actually happen?

The status bar does not overlay the WebView

## Information

1. Create a new project
    - `cordova create ./cordovaTest`
2. Add plugin
    - `cordova plugin add https://github.com/apache/cordova-plugin-statusbar.git`
3. Modify `config.xml` to add this inside `<widget/>`:
    - `<preference name="StatusBarOverlaysWebView" value="true" />`
4. Add iOS platform:
    - `cordova platform add ios`
5. Prepare iOS platform:
    - `cordova prepare ios`
6. Open Xcode project
    - `open ./platforms/ios/HelloCordova.xcworkspace`
7. Run in an iPhone 8 simulator
8. Observe that the status bar is not overlaying the WebView. Status bar is white
9. Open a web inspector from safari for the WebView
10. Run:
    - `StatusBar.overlaysWebView(true)`
11. Observe status bar still doesn't overlay webview
12. Run:
    - `StatusBar.hide()`
13. Observe the status bar is hidden (so the library works)

### Environment, Platform, Device

- *Device:* iPhone 8, and iPhone 8 Simulator
- *Platform:* iOS

### Version information

- **Device:** iPhone 8 (simulator)
- **Device OS:** iOS 13 (and 13.1)
- **Cordova:** 9.0.0 (cordova-lib@9.0.1)
     - **Platform:** ios 5.0.1
- **Plugin:** 2.4.3 (also tried the repo)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by kkirby** [comment]
Solved (ish).

Apparently you now need to tell the WebView to fill the screen via an additional viewport property. I found the solution here: https://stackoverflow.com/a/46208264/701263

Add this to the viewport meta:

`viewport-fit=cover`

And it works perfectly.

**Comment by jcesarmobile** [comment]
It’s like that since iOS 11

**Comment by kkirby** [comment]
@jcesarmobile Is this said anywhere in the plugin's documentation?

**Comment by jcesarmobile** [comment]
It doesn't have anything to do with the plugin. But could be mentioned on the quirks section (it isn't at the moment)

**Comment by brodybits** [comment]
> Is this said anywhere in the plugin's documentation?

A PR to document this in the quirks section would be very welcome.

**Comment by puppyriver** [comment]
I set viewport-fit=cover ,but it still doesn't work, anybody can help?  (IOS.13)

**Comment by kkirby** [comment]
@puppyriver Try my steps in the original issue but modify the viewport meta tag to reflect this:

```html
<meta name="viewport" content="initial-scale=1, width=device-width, viewport-fit=cover">
```

If the status bar still doesn't overlay the WebView then post what versions you are using of Cordova and cordova-platform-ios.

**Comment by mantou132** [comment]
Sometimes working, sometimes not working

**Comment by Finedl** [comment]
I encountered the same problem, I can use it normally on Android but not on IOS. I modified< meta  name =“ viewport ” content =“ initial-scale = 1，width = device-width，viewport-fit = cover ” > but failed

**Comment by muhammad-gul-dm** [comment]
> Solved (ish).
> 
> Apparently you now need to tell the WebView to fill the screen via an additional viewport property. I found the solution here: https://stackoverflow.com/a/46208264/701263
> 
> Add this to the viewport meta:
> 
> `viewport-fit=cover`
> 
> And it works perfectly.

Working 100%
