### ISSUE TITLE
StatusBar overlays WebView after using Cordova Camera plugin in iOS 13

### ISSUE THREAD

**Issue by ISeeBinary** [apache/cordova-plugin-statusbar#167]
# Bug Report

## Problem
The StatusBar overlays the WebView on iOS 13 after using the camera plugin (cordova-plugin-camera), even if "StatusBarOverlaysWebView" is set to false.

### What is expected to happen?
The StatusBar should not overlay the WebView when returning from the camera.

### What does actually happen?
The StatusBar overlays the WebView when returning from the camera.

## Information
Launch the app and the StatusBar should behave as expected (does not overlay the WebView). Now launch the camera via the cordova plugin, take a picture (or cancel out), and on returning to the app, the StatusBar is now overlaying the WebView. To correct it you can change the device orientation, which seems to reset the StatusBar / WebView.

### Command or Code
Please see the following GitHub repository:

https://github.com/ISeeBinary/StatusBarTestApp

When running the example you will see a red button at the top of the screen that launches the camera. There is also a green button for toggling the StatusBar on and off. This is because calling StatusBar.hide followed by StatusBar.show also seems correct its behaviour.

### Environment, Platform, Device
- iPhone XS (iOS 13.1.3)

### Version information
- cordova@9.0.0 (also reproduced with cordova@8.1.2)
- cordova platform ios@5.0.1
- cordova-plugin-statusbar@2.4.3
- cordova-plugin-camera@4.1.0

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
This issue should be fixed by https://github.com/apache/cordova-plugin-statusbar/pull/157

You can get the patch if you install the statusbar plugin from git e.g.:

`cordova plugin add https://github.com/apache/cordova-plugin-statusbar.git`

Or if you want to protect yourself from unexpected changes, you can fork the statusbar plugin and install from your own fork.

Let me know if this helps you.

**Comment by ISeeBinary** [comment]
Much appreciated. Thanks.

**Comment by breautek** [comment]
You're welcome.

**Comment by landabaso** [comment]
Hey guys, is it there any planned release including this patch?
