### ISSUE TITLE
statusbar overlaysWebView defaults to true not work on android

### ISSUE THREAD

**Issue by huiofe** [apache/cordova-plugin-statusbar#174]
# Bug Report

## Problem
onDeviceReady I set overlaysWebview to true, but it's not work. But it worked again when system keyboard show. That is very strange!!  I used this plugin on android 8.0
## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
duplicate of https://github.com/apache/cordova-plugin-statusbar/issues/158
