### ISSUE TITLE
Statusbar renders white halfway when SafariViewController is presented, rotated and closed

### ISSUE THREAD

**Issue by AUK4GIT** [apache/cordova-plugin-statusbar#179]
# Bug Report
My App is locked to work in portrait orientation on iPhones. I have used cordova-plugin-safariviewcontroller to present an external link. The SafariViewcontroller can be rotated in all orientations. Now, opening SafariViewController in portrait, rotating to landscape, then back to portrait and closing it would render the Statusbar with white color halfway.
## Problem
![Statusbar_Orientation_issue](https://user-images.githubusercontent.com/6498990/75158772-df0c4900-573c-11ea-98cb-066b8a390be1.gif)

### What is expected to happen?
The expectation is that the statusbar color should be retained full width.

### Command or Code

      statusBar.overlaysWebView(false);
      statusBar.styleDefault();
      statusBar.backgroundColorByHexString('#B2D5E4');

### Version information

"cordova-plugin-statusbar": "^2.4.3"

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
should be fixed by https://github.com/apache/cordova-plugin-statusbar/pull/157
