### ISSUE TITLE
styleDefault() and styleLightContent() is not work in android 10 emulator.

### ISSUE THREAD

**Issue by jenerse** [apache/cordova-plugin-statusbar#185]
# Bug Report

## Problem
StatusBar.styleDefault() is not work in android 10 emulator. 
And I run StatusBar.styleDefault() in android 9 is work.

### What is expected to happen?
When I run `StatusBar.styleDefault()` in debugger,  the status bar will become to default style from light style

### What does actually happen?
When I run `StatusBar.styleDefault()` the status bar have not any changes.

### Command or Code

If the status bar is light. please run `StatusBar.styleDefault()` in debugger.
If the status bar is dark. please run `StatusBar.styleLightContent()` in debugger.

### Environment, Platform, Device

Android 10 emulator.

### Version information
Cordova: cordova@9.0.0,  cordova-android@8.1.0 , cordova-plugin-statusbar@2.4.3

Android Studio@3.6.1

Android sdk version: 10

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by aacassandra** [comment]
can you explain why you closed this @jenerse ? I also experience problems when running on Android 7.1.1 device
