### ISSUE TITLE
after opening iphone gallery Statusbar overlaywebview(false) changes to true.

### ISSUE THREAD

**Issue by gohar1009** [apache/cordova-plugin-statusbar#186]
# Bug Report

## Problem
I have camera plugin, and statusbar overlaywebview is setted to false. When I open the gallery statusbar started overlay webview so I have problem with style.
### What is expected to happen?
I need overlaywebview stayed to false.

### Environment, Platform, Device

I have the problem with ios devices.

### Version information

Cordova, Ionic, Xcode

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by netodeolino** [comment]
I have the same problem! I need help with this...

**Comment by gohar1009** [comment]
Hi. After closing gallery set overlaywebview to true then again to false.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
