### ISSUE TITLE
There is something like a navigation bar on some ios devices

### ISSUE THREAD

**Issue by skozgursk** [apache/cordova-plugin-statusbar#193]
Even tough my project has no navigation bar when ı open it always put someting like it. There is always 50px space over home button. it happens on some ios devices for example xs and 11. I think it related with new home button ı am not sure. After I switch between apps or show ads its disappears.

this is on my info.plist
`
<key>UIStatusBarHidden</key>
<true/>
<key>UIViewControllerBasedStatusBarAppearance</key>
<false/>
`

index.html

`<meta name="viewport" content="viewport-fit=cover, initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width, height=device-height" />
`
config.xml

`<preference name="StatusBarDefaultScrollToTop" value="false" />
        <preference name="StatusBarOverlaysWebView" value="true"/>
        <preference name="StatusBarBackgroundColor" value="#000000"/>
        <preference name="StatusBarStyle" value="blackopaque"/>
        <preference name="BackgroundColor" value="#ffffff"/>
        <preference name="DisallowOverscroll" value="true"/>
        <preference name="WebViewBounce" value="false"/>
        <preference name="KeyboardShrinksView" value="true"/>
        <preference name="Allow3DTouchLinkPreview" value="false"/>
        <preference name="DetectMediaTypes" value="true"/>
        <preference name="allowInlineMediaPlayback" value="true"/>
        <preference name="AllowInlineMediaPlayback" value="true"/>`

Example image on open

![Simulator Screen Shot - iPhone Xs Max - 2020-06-30 at 16 09 16](https://user-images.githubusercontent.com/45282949/86129289-1fb11000-baeb-11ea-97a4-fef84f3ff01b.png)

Example image after ads

![Simulator Screen Shot - iPhone Xs Max - 2020-06-30 at 16 12 34](https://user-images.githubusercontent.com/45282949/86129569-92ba8680-baeb-11ea-8c5e-19f810369ef4.png)

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
