### ISSUE TITLE
status bar overlaied app header when statusBar.overlaysWebView(true)

### ISSUE THREAD

**Issue by JayzeeHuang** [apache/cordova-plugin-statusbar#197]
# Bug Report

## Problem
Shown as screenshot
![Screenshot_20200818_160728_nz co vdot www](https://user-images.githubusercontent.com/8422031/90469975-5f50bb80-e16e-11ea-99cf-0f1eb90e3d9c.jpg)

### What is expected to happen?

Status bar and header should be sperated

### What does actually happen?

looks padding top get no values

## Information

not sure if i am the only one

### Command or Code

ionic corodva run android --prod --release

### Environment, Platform, Device

ionic cordova android platform
ios works perfect

### Version information

Ionic:

   Ionic CLI                     : 6.11.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.901.8
   @angular-devkit/schematics    : 9.1.8
   @angular/cli                  : 9.1.8
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 8.1.0, ios 6.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 22 other plugins)

Utility:

   cordova-res (update available: 0.15.1) : 0.13.1
   native-run                             : 1.0.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.16.2 (/usr/local/bin/node)
   npm        : 6.14.5
   OS         : macOS Catalina
   Xcode      : Xcode 11.6 Build version 11E708

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
`statusBar.overlaysWebView(true)` makes it so the statusbar is overlaid the webview... or in otherwords, the webview is full screen. It will be up to you to add the necessary padding/margins to ensure your UI is placed appropriately.

By the sounds of it, it looks like you want `statusBar.overlaysWebView(false)`, so that the webview starts just below the statusbar.

**Comment by JayzeeHuang** [comment]
@breautek 
Thanks for your reply
I tried statusBar.overlaysWebView(false)
![Screenshot_20200818_172124_nz co vdot www](https://user-images.githubusercontent.com/8422031/90473840-fb32f500-e177-11ea-87d7-fe4a4848f020.jpg)

**Comment by breautek** [comment]
Are you able to provide an [example app](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) that reproduces the problem?

I can take a look later tonight.

**Comment by JayzeeHuang** [comment]
Hi, solved this by myself, I looked up some codes, seems Android platform safe-inset-top always zero and the framework set the defult value also zero. Just need to be manully set the defult to 25px will fixed.
