### ISSUE TITLE
Uncaught exception 'NSRangeException'

### ISSUE THREAD

**Issue by Zapmobilegames** [apache/cordova-plugin-statusbar#206]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Description
Just run the app and read in the log:

Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSConcreteScanner setScanLocation:]: Index 1 out of bounds; string length 0'
*** First throw call stack:
(0x1a4b39114 0x1b835fcb4 0x1a5ce0418 0x104bb4194 0x104bb2a78 0x104bc5648 0x104bc5b44 0x104bc31a0 0x104ab0bf4 0x1a6cb6adc 0x1a6cbb130 0x1a6cbb510 0x1a73b64b0 0x1a73b5cc4 0x1a73b6b58 0x1a73c77b0 0x104bb54b0 0x104ab0908 0x1a7374558 0x1a73764f8 0x1a737bcac 0x1a6a5ac4c 0x1a6f7d82c 0x1a6a5b734 0x1a6a5b23c 0x1a6a5b560 0x1a6a5ae1c 0x1a6a629bc 0x1a6e970a0 0x1a6f9510c 0x1a6a62754 0x1a68a49b4 0x1a68a3454 0x1a68a4600 0x1a7379e80 0x1a6ebd914 0x1b33b7cb4 0x1b33df6e0 0x1b33c5410 0x1b33df3f4 0x104e9d5fc 0x104ea0ac4 0x1b34044b8 0x1b3404180 0x1b3404654 0x1a4ab9240 0x1a4ab9140 0x1a4ab8488 0x1a4ab2a40 0x1a4ab2200 0x1babad598 0x1a7378004 0x1a737d5d8 0x104ab0810 0x1a4791598)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSConcreteScanner setScanLocation:]: Index 1 out of bounds; string length 0'
terminating with uncaught exception of type NSException

### Environment, Platform, Device

I found this log using:
Mac OS: 10.15.7 (Catalina)
XCode:  12.1
iOS (iPhone): 14
Cordova 6.1.1

### Version information

Plugin Version: 3.0.0-dev

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by faugusztin** [comment]
Any reason you are reporting this against the statusbar plugin ? Reason being `-[NSConcreteScanner setScanLocation:]: Index 1 out of bounds; string length 0'`, which is not part of this plugin. Maybe you are using cordova-plugin-safariviewcontroller, which contains said code ?

**Comment by breautek** [comment]
Closing this issue as invalid. The mentioned code is not from this plugin.
