### ISSUE TITLE
StyleDefault will set light text instead of dark.

### ISSUE THREAD

**Issue by crazyserver** [apache/cordova-plugin-statusbar#213]
# Bug Report

## Problem

When dark mode is selected on the iOS settings, if you have a white background, using styleDefault will use light text instead of dark.  Also tested using styleBlackOpaque with the same behaviour.

When dark mode is disabled, styleDefault will use dark text as expected.

Probably a new function styleDarkContent is needed.

### What is expected to happen?

Using styleDefault should use dark text.

### What does actually happen?

Using styleDefault will use light text instead of dark.

## Information

1. Open iOS system settings and set dark mode.
2. Open the app, and check white over white is applied.

### Command or Code

```
    StatusBar.overlaysWebView(false);
    StatusBar.backgroundColorByHexString('#FFFFFF');
    StatusBar.styleDefault();
```

### Environment, Platform, Device

Using latest version 2.4.3
iOS 14.5 or 14.6

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by tobeagram** [comment]
#181 PR Request adds `styleDarkContent` – creating a new way to modify the status bar text to be dark on a white background.

**Comment by jcesarmobile** [comment]
in version 3 of the plugin the StyleDefault will set the status bar to black text as documented
