### ISSUE TITLE
iOS - HTML video player full screen causes web view overlay issues

### ISSUE THREAD

**Issue by famousglasses** [apache/cordova-plugin-statusbar#221]
iPhone Xr
iOS 14.6

When using the status bar plugin with `overlaysWebView(false)`, I am noticing that using the native html video player in full screen mode will at times cause a reverting of the overlaysWebView property.

Note: after this error occurs, it can be fixed during runtime by executing this code -- `overlaysWebView(true); overlaysWebView(false);`

Scenario A - Steps to reproduce:
1. Setup app to use `overlaysWebView(false)`
2. With page containing video player, use the player controls to toggle full screen mode
3. Rotate device to trigger landscape mode
4. Rotate device to trigger portrait mode
5. Close the player using the "X" icon near the top left of the screen
6. Status bar now overlays web view

Scenario B - Steps to reproduce:
1. Setup app to use `overlaysWebView(false)`
2. With page containing video player, use the player controls to toggle full screen mode
3. Close video player by swiping down on the screen
4. Status bar now overlays web view

Before error occurs:
![example1](https://user-images.githubusercontent.com/13125441/136265639-a8826a2b-01dd-43ad-bc7c-419f86683a53.png)

After error occurs:
![example2](https://user-images.githubusercontent.com/13125441/136265647-21777840-9de4-4d32-9f8c-573fc07cac78.png)

**Comment by jcesarmobile** [comment]
Can you try with latest version of the plugin? I think it was fixed long ago but not released until the 3.0.0 version

**Comment by jcesarmobile** [comment]
Closing since there was no response
