### ISSUE TITLE
Empty space below the status bar on devices without notch and iOS 15.4

### ISSUE THREAD

**Issue by ordas** [apache/cordova-plugin-statusbar#225]
Hi!

We are having a problem with iOS 15.4, on devices without notch (ex: iPhone 6) and overlaysWebView(false).
Below the status bar there is a 20px empty space (similar to the status bar itself) which the application does not cover.
However it works perfectly on iOS 14 and earlier.

The project is developed in ionic 3 and the version of the statusbar plugin is 3.0.0.

Can you help me?

Thank you!
![issue](https://user-images.githubusercontent.com/3008680/158987599-199d7d98-0802-4a66-a123-daf0bfa25d64.jpg)

**Comment by jcesarmobile** [comment]
can you provide a sample app where the issue can be reproduced?

**Comment by ordas** [comment]
Of course! Can you give me your email and I'll send you the app?

**Comment by ordas** [comment]
@jcesarmobile Thank you very much, but it is not necessary :-) We have solved the problem.

Solution
- Update ionic
- update cordova
- Update iOS SDK (Xcode)

**Comment by jcesarmobile** [comment]
Cool, thanks for letting us know.
