### ISSUE TITLE
backgroundColorByHexString does not work?

### ISSUE THREAD

**Issue by bublikOff** [apache/cordova-plugin-statusbar#254]
Trying to use status bar plugin with cordova@11

config.xml
```
    <preference name="StatusBarOverlaysWebView" value="false" />
    <preference name="StatusBarBackgroundColor" value="#ffa726" />
```

In html app Im trying to change color manually according to scroll position but have no luck. 
It keeps original #ffa726 color

```
if(cordova.platformId == 'android')
{
    StatusBar.backgroundColorByHexString(page.scrollTop > 30 ?  '#ffff' : '#ffa726');
}
```

**Comment by jcesarmobile** [comment]
Can you provide a sample app?
`#ffff` is not a valid value, it should be 6 digits `#ffffff` or 3 digits `#fff`, but not 4.

**Comment by bublikOff** [comment]
My fault .. Cordova variable was overridden in app by local dummy data about Cordova
