### ISSUE TITLE
StatusBar still there, stopped to work

### ISSUE THREAD

**Issue by sunco007** [apache/cordova-plugin-statusbar#267]
Hello, I'm using cordova-plugin-statusbar 3.0.0 and I want to hide both bars.

This command used to work for me, but I **didn't realize when it stopped working, maybe since I started testing on a more modern device**. Without the 'true' parameter, it doesn't work:

```javascript
StatusBar.hide(true);
```

What this command does is hide the top bar, but the bottom one still appears.

Using the following line in config.xml does the opposite, it shows the top and bottom bars:

```xml
<preference name="StatusBarOverlaysWebView" value="false" />
```

The device is a Samsung Galaxy A22 running Android 13.

I'm not sure if it matters, but it has One UI Core 5.1 installed (it's my daughter's phone).

According to what I see in the code, I had already tried this:

```xml
<preference name="StatusBarOverlaysWebView" value="false" />
<preference name="StatusBarCropsWebview" value="true" />
<preference name="StatusBarStyle" value="blackopaque" />
<preference name="StatusBarBackgroundColor" value="#2980b9" />    
<preference name="TopActivityIndicator" value="black" />
```

The minSdkVersion is 21

cordova -v = 12.0.0 (cordova-lib@12.0.1)

cordova plugin list:

cordova-plugin-device 2.1.0 "Device"
cordova-plugin-dialogs 3.0.0-dev "Notification"
cordova-plugin-inappbrowser 5.0.0 "InAppBrowser"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 6.0.1 "Splashscreen"
cordova-plugin-statusbar 3.0.0 "StatusBar"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-x-socialsharing 6.0.4 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"

**Comment by jcesarmobile** [comment]
can you provide a sample app?
